### ISSUE TITLE
React Native Setup

### ISSUE THREAD

**Issue by phillipkey** [fullstorydev/fullstory-react-native#17]
I find the documentation very lacking on setup steps for React-Native. 

It says to follow the iOS and Android setup but not how we are supposed to make the fullstory implementation available across the JS bridge.

There is nothing to let the developer know how to install this fully.

**Comment by sabrina-li** [comment]
Hi phillipkey,
Sorry to hear the confusion around documentation, this plug-in is intended to be used in conjunction with FullStory for Mobile Apps. 
To add FullStory for Mobile Apps, follow the guide for [Android](https://help.fullstory.com/hc/en-us/articles/360040596093-Getting-Started-with-Android-Recording) and [iOS](https://help.fullstory.com/hc/en-us/articles/360042772333-Getting-Started-with-iOS-Recording). 
Once they are set up, follow the [React Native](https://help.fullstory.com/hc/en-us/articles/360052419133-Getting-Started-with-FullStory-React-Native-Recording) guide to set up this plugin to bridge across to JS to use the APIs.

In the future, please feel free to reach out to mobile-support@fullstory.com if you need any assistance with the React Native plugin or other Mobile recording support and our team will be happy to assist.
