### ISSUE TITLE
getCurrentSession returns null

### ISSUE THREAD

**Issue by kunalhemrajani** [fullstorydev/fullstory-react-native#18]
Hi Team,

Having followed the docs https://help.fullstory.com/hc/en-us/sections/360007387073-FullStory-for-Mobile-Apps for the setup for setting FS for mobile on our react native app, we can't seem to get the recordings showing up in the FS dashboard.

A bit of debugging showed that both `getCurrentSession` and `getCurrentSessionURL` are being returned as null.

Any ideas on how to resolve this or any steps around debugging. The only documentation I found for debugging was for the web applications.

```
"react-native": "0.63.3",
"@fullstory/react-native": "^1.0.1"
v1.8.2 being used for native
```

PS: Another interesting thing I noticed and that might help is while building for the android simulator, there was a message which said `FullStory: React Native - Unable to detect React Native Javascript bundle - runtime support might be limited`, I did the setup twice just to ensure I didn't miss anything but that didnt help.

**Comment by sabrina-li** [comment]
Hi Kunal,
Sorry to hear you’re running into issues implementing React Native. We noticed that you've created a ticket with FullStory support team. I wanted to confirm that we've received your request and will be getting back to you shortly regarding setting up your org to resolve this issue. In the future, feel free to reach out to mobile-support@fullstory.com if you need any assistance with the React Native plugin or other Mobile recording support.

**Comment by BeaRRRRR** [comment]
@kunalhemrajani Hi, did you manage to fix it? I'm facing the same problem and would love to know the solution. Thanks!

**Comment by kunalhemrajani** [comment]
Hi @BeaRRRRR for me it was because the mobile recording wasn't enabled on my org. It is definitely worth reaching out to the mobile support team, they are super helpful and would help you in getting this over the line.
