### ISSUE TITLE
react native demo 

### ISSUE THREAD

**Issue by mohamed-sultan** [fullstorydev/fullstory-react-native#19]
thank you for this awesome package 
it seems to be a need for example demo on react native 
for android i get an error and  i don't know where to add exactly on app level build.gradle 

fullstory {
  org '<YOUR ORG ID HERE>'
}
also when try to start on ios i get
Error ["shared-core/src/session/mod.rs"]: Recording not enabled, please check org and server (org = *****, server = https://mr.fullstory.com, status = 202, response = reason_code: 2
)

**Comment by sagartrehan** [comment]
@mohamed-sultan I am getting same error. Are you able to fix it??

**Comment by jwise** [comment]
Hi @mohamed-sultan and @sagartrehan -- we aren't set up to answer support inquiries via GitHub right yet.  If you're having trouble setting up FullStory for React Native, please reach out to support at mobile-support@fullstory.com.  Thanks!
