### ISSUE TITLE
Build fails when running from terminal, works fine when running from Android Studio

### ISSUE THREAD

**Issue by robotnoises** [fullstorydev/fullstory-react-native#20]
Hi!

Sorry if this is a silly question, but I'm currently unable to build our app with FullStory via the terminal with the following script:

```
react-native run-android --variant=StagingDebug --appIdSuffix=staging.debug
```

I get the following output:

```
> Task :app:fullstoryStagingDebug
Applying FullStory to variant 'stagingDebug'...
Detected FullStory React Native plugin...
FullStory: React Native - Unable to detect React Native Javascript bundle - runtime support might be limited
Uploading resources...

> Task :app:fullstoryStagingDebug FAILED
```

It always runs just fine when I start it in Android Studio.

React Native version: `0.63.4`
FullStory RN version: `1.0.1`

**Comment by jwise** [comment]
Hi @robotnoises -- sorry for the delay.  As you may have noticed, we aren't set up to answer support inquiries via GitHub right yet.  If you're still having trouble setting up FullStory for React Native, please reach out to support at mobile-support@fullstory.com and we'll do our best to get you all set up.  Thanks!
