### ISSUE TITLE
Unable to build project

### ISSUE THREAD

**Issue by kusalshrestha** [fullstorydev/fullstory-react-native#23]
Issue:
```
> Could not resolve all artifacts for configuration ':classpath'.
   > Could not find com.fullstory:gradle-plugin-local:1.15.0.
     Searched in the following locations:
       - https://dl.google.com/dl/android/maven2/com/fullstory/gradle-plugin-local/1.15.0/gradle-plugin-local-1.15.0.pom
       - https://jcenter.bintray.com/com/fullstory/gradle-plugin-local/1.15.0/gradle-plugin-local-1.15.0.pom
```

React native: `0.63.2`

Followed -> https://help.fullstory.com/hc/en-us/articles/360052419133
https://help.fullstory.com/hc/en-us/articles/360040596093-Getting-Started-with-Android-Recording

**Comment by iamrajshekhar** [comment]
Whenever i am running the application or trying to build it.  am getting this error
**Unable to determine FullStory version, please verify your root build file is properly configured**
and 

**Could not find com.fullstory:instrumentation-full:null.**

Can you please look into it.

**Comment by jwise** [comment]
Hi @kusalshrestha and @iamrajshekhar -- unfortunately, we're not set up to handle support over GitHub right now.  If you send mail to our mobile support team at at mobile-support@fullstory.com , we'll do our best to get you all set up. Thanks!
