### ISSUE TITLE
fsTagName is not a valid JSX prop

### ISSUE THREAD

**Issue by elliottkember** [fullstorydev/fullstory-react-native#25]
Hi there,

I'm trying to get FullStory integrated into my React Native app, but found that I had issues in TypeScript when adding the `fsTagName` / `fsClass` attributes to my elements:

```
Property 'fsTagName' does not exist on type 'IntrinsicAttributes & IntrinsicClassAttributes<Text> & Readonly<TextProps> & Readonly<{ children?: ReactNode; }>'.ts(2769)
```

A workaround here would be to also enable `fs-tag-name` and `fs-class` - these are allowed as arbitrary attributes in JSX and won't cause type errors.

**Comment by elliottkember** [comment]
@nfriedly Just saw your reply - I'm happy to help test. I also have some folks who are more adept with TypeScript who may be able to help. I'll keep you posted.

**Comment by elliottkember** [comment]
@nfriedly I think it's this:

```
declare namespace JSX {
  interface IntrinsicAttributes {
    fsTagName?: string;
    fsClass?: string;
  }
}
```

**Comment by nfriedly** [comment]
Oh, interesting. Thanks!

**Comment by nfriedly** [comment]
Ok, for the moment, we're going to recommend that you add the declarations to your own code, pretty similar to what you posted above:


```tsx
declare global {
  namespace JSX {
    interface IntrinsicAttributes {
      fsAttribute?: string;
      fsClass?: string;
      fsTagName?: string;
    }
  }
}

export {};
```

More info at https://help.fullstory.com/hc/en-us/articles/360052419133#01ER0FBDCZE1RMZ5NWT4ZC8D4Q

**Comment by rcmaples** [comment]
Hi there @elliottkember, RC here with FullStory's support engineering team. I'm going to go ahead and close this issue since we're not really set up to provide support via Github issues. If you're still having trouble here feel free to reach out to mobile-support@fullstory.com and we'll jump in to help out.

All the best
