### ISSUE TITLE
Missing letters in text

### ISSUE THREAD

**Issue by elliottkember** [fullstorydev/fullstory-react-native#26]
This is a fun one. The FullStory plugin is missing characters from my views. I noticed this because my name is "Elliott" and yet it is shortened to "Elliot" all over the place in my app. I've also noticed it changes "setting" to "seting", and "automatically" to "automatcally".

I really have no idea how this is possible. Isn't the text read from the component?

**Comment by jwise** [comment]
Hi Elliott.  That *is* a fun one!  Thanks for your keen eye.  Unfortunately, we're not really set up to handle support via GitHub right now.  Can you send some mail to mobile-support@fullstory.com?  This sounds like a good issue that I'd like to track, and the best way to make sure it's on my radar is to make sure it gets through the support flow.

**Comment by elliottkember** [comment]
@jwise Done. I sent through a few issues in one email. I actually think I know what this is - we use a custom font which is kerning these letters together. 

![image](https://user-images.githubusercontent.com/42827/130526485-43271c07-469b-4f73-87ff-d92e9a952458.png)
