### ISSUE TITLE
Task runs on every build because it declares no outputs.

### ISSUE THREAD

**Issue by Gerlison** [fullstorydev/fullstory-react-native#28]
## Description

The app build is taking about 30 sec on the fullstory build task, which was accused by android studio of not have outputs declared. Logs below

## Logs from Android Studio

At 09:55, Sep 07, 2021, Android Studio detected the following issue(s) with Gradle plugin fullstory

Always-Run Tasks
Task runs on every build because it declares no outputs.

Plugin: fullstory
Task: fullstoryRegularRelease
Task type: org.gradle.api.DefaultTask
Issues for the same task were detected in 1 module(s), total execution time was 28.0s (12.0%), by module:
  Execution mode: FULL, time: 28.0s (12.0%), determines build duration: true, on critical path: false, issues: Always-Run Tasks

====Build information:====
Execution date: 9/7/21 9:55 AM
Total build duration: 242.7s
Configuration time: 3.0s (1.2%)
Critical path tasks time: 234.4s (96.6%)
Critical path tasks size: 233
AGP versions: 4.1.0
====Platform information:====
AI-201.8743.12.41.6953283, JRE 1.8.0_242-release-1644-b3-6915495x64 JetBrains s.r.o, OS Mac OS X(x86_64) v10.16, screens 1440x900; Retina

AS: 4.1.1; Kotlin plugin: 1.3.72-release-Studio4.1-5; Android Gradle Plugin: 4.1.0; Gradle: 6.7; NDK: from local.properties: (not specified), latest from SDK: (not found); LLDB: pinned revision 3.1 not found, latest from SDK: (package not found); CMake: from local.properties: (not specified), latest from SDK: (not found), from PATH: (not found)

**Comment by rcmaples** [comment]
Hi there @Gerlison, RC here with FullStory's support engineering team. Sorry to hear about the trouble you've run into and sorry for the extreme delay in getting back to you. We're not really set up to provide support via Github issues. If you're still having trouble please reach out to mobile-support@fullstory.com and we'll be happy to help.

Cheers
