### ISSUE TITLE
 getCurrentSessionURL  NULL

### ISSUE THREAD

**Issue by MuhammadAdnan384** [fullstorydev/fullstory-react-native#29]
@Joshua Humphries
@sabrina-li 

 getCurrentSessionURL {"_U": 0, "_V": 0, "_W": null, "_X": null}

Even though we complete all configuration for android with react native from documentation but still current session url null. i don't know why this happening. 

 https://help.fullstory.com/hc/en-us/articles/360052419133-Getting-Started-with-FullStory-React-Native-Recording

https://help.fullstory.com/hc/en-us/articles/360040596093-Getting-Started-with-Android-Recording

i also try given sdk (https://github.com/fullstorydev/react-native-shoppe-demo) but there is not ORG ID (null) in build.gradle file

**Comment by sabrina-li** [comment]
Hi @MuhammadAdnan384, 

Thanks for reaching out and filing an issue with us here on Github. Sorry to hear that you are running into issues with `getCurrentSessionURL`. For assistance in setting up your app with FullStory for Mobile Apps, please reach out to mobile-support@fullstory.com and our support team would be happy to assist with any questions.

Kind regards,
Sabrina
