### ISSUE TITLE
Android build :app:assembleDebug not functional (java.util.ConcurrentModificationException)

### ISSUE THREAD

**Issue by TannerLessen** [fullstorydev/fullstory-react-native#32]
I have already submitted a support ticket to mobile-support@fullstory.com as advised, but I'm crossposting for visibility and on the off-chance the community has a solution...

I have successfully installed and configured everything to enable recording on both iOS and Android, however we are running into errors when attempting to build our Android app both from Android Studio as well as from the command line.

The build works when we execute `./gradlew assembleDebug` (from CLI) however we do not regularly work from the command line and would like to rectify this issue to allow our developers to continue to build and test from Android Studio.
 
The build error occurs when running `./gradlew :app:assembleDebug` (from Android Studio or CLI):

 ```
Could not determine the dependencies of task ':app:compileDebugJavaWithJavac'.
> Could not resolve all dependencies for configuration ':app:debugCompileClasspath'.
   > java.util.ConcurrentModificationException (no error message)
 ```

MultiDex is explicitly enabled
I have tried on SDK 30 and 31
I have tried upgrading to Gradle 7+
I have tried different build tools versions
I have updated all my local SDK tools
I have verified the same issue occurs with other developers
 
Versions:
Android Studio: 2020.3.1 Patch 4
react: 17.0.2
react-native: 0.66.1
@fullstory/react-native: 1.0.3
multidex: 2.0.1

build.gradle
```
buildscript {
    ext {
        buildToolsVersion = "30.0.2"
        minSdkVersion = 21
        compileSdkVersion = 31
        targetSdkVersion = 31
        ndkVersion = "21.4.7075529"
        kotlinVersion = '1.5.31'
    }
    repositories {
        google()
        mavenCentral()
        maven { url "https://maven.fullstory.com" }
    }
    dependencies {
        classpath('com.android.tools.build:gradle:4.2.2')
        classpath "org.jetbrains.kotlin:kotlin-gradle-plugin:$kotlinVersion"
        classpath 'com.google.gms:google-services:4.3.10'
        classpath 'com.fullstory:gradle-plugin-local:1.22.0'
        // NOTE: Do not place your application dependencies here; they belong
        // in the individual module build.gradle files
    }
}
```

app/build.gradle
```
apply plugin: 'fullstory'
fullstory {
    org '<redacted>'

    // By default, FullStory is applied only to release build variants.
    // e.g. 'debug', or 'debug|release' for multiple targets.
    enabledVariants 'all'

    // FullStory records any Log statements at and above INFO level by default.
    // logLevel 'error'

    // By default, FullStory will automatically request a session and start recording on app startup.
    // If set to false, FullStory will only record when FS.restart() is called.
    recordOnStart false
}
```

Any help is greatly appreciated! I'm hopeful it's just something simple I have overlooked or version mismatches. Hopefully not some unfortunate race condition, though it feels like that at the moment.

I have verified with certainty that the FullStory integration is the culprit, as removing it again allows the builds to run smoothly. I have also built and installed manually and verified the library works on both platforms just fine so it's solely a build issue for us right now.

**Comment by rcmaples** [comment]
👋  Hi Tanner; RC here. I've got your ticket in the support queue and I'll be following up with you shortly!
