### ISSUE TITLE
Main queue dispatch and import

### ISSUE THREAD

**Issue by devladinci** [fullstorydev/fullstory-react-native#5]
👋,
Thanks for the great work!
 Couple of suggestions regarding iOS module.

* No need to dispatch every single function to the main queue eg. `dispatch_async(dispatch_get_main_queue(), ^{ ` you can just declare 
`- (dispatch_queue_t)methodQueue {
    return dispatch_get_main_queue();
}`

* I had troubles with the import, maybe it was just me. But the import of full story pod should be inside the implementation file not the header. Instead of importing just the `FS.h`, I think should be the general export `#import <FullStory/FullStory.h>`

And last one, maybe not related to this repo.

It'd be nice to disable FullStory recording on dev env:
```
if [ "! ${CONFIGURATION}" == "Debug" ]; then
"${PROJECT_DIR}/Pods/FullStory/tools/FullStoryCommandLine" "${CONFIGURATION_BUILD_DIR}/${WRAPPER_NAME}"
fi
```
should be the script included in the build phases.

**Comment by JoshMiers-FS** [comment]
@devladinci - thanks for the great feedback!

I will file an issue on our internal tracker to track your suggestions.
